### ISSUE TITLE
Undamaged Structures Need Visualization/Accounting

### ISSUE THREAD

**Issue by mflaxman10** [RandomFractals/paradise-campfire-map#2]
Current behavior

Undamaged structures in point data only reflect subset of those in polygon data.  In the polygon data, v3, there are two possible codes for undamaged - "other" and "" .    The blank ones don't render in the point version.

Expected behavior
Want to show and actually highlight cartographically those buildings which were exposed but survived.  Don't really know what "other" means (no metadata).  So propose two categories: "Exposed, no damage" and "Not exposed".   Lacking further clarifications, I'd reclassify "Other" into "Exposed, no damage"

**Comment by RandomFractals** [comment]
Originally, we set our damage categories to ```const labels = {
  "Destroyed (>50%)": ">50%",
  "Major (26-50%)": "26-50%",
  "Minor (10-25%)": "10-25%",
  "Affected (1-9%)": "1-9%",
  "Other": "Other"
};
```
if those need to change per your v3 data set, you can remap those labels and colors in damage-color-palette.js config: https://github.com/RandomFractals/paradise-campfire-map/blob/master/src/common/damage-color-palette.js and vega-spec.js if things changed on your end since then.
